### ISSUE TITLE
Short cut keys activate when entering text

### ISSUE THREAD

**Issue by kwadroke** [exokitxr/multiplayer#28]
Create a room with the letter g, or type g in chat, the screen goes full screen.
When editing Code, pressing Enter activates chat instead of entering a blank line.

How I expected it to react:
If text boxes are in focus (code & new room name) , do not activate Chat (Enter) or Full screen (G).

I'm figure other short-cut keys can be activated as well.

**Comment by avaer** [comment]
Whoops, yeah, it should definitely not be consuming the g shortcut when something is focused...

**Comment by avaer** [comment]
Should be fixed now.

**Comment by kwadroke** [comment]
Still seeing this issue when editing text (using 1-4) in the Code section of the UI. Letters aren't having the problem

**Comment by avaer** [comment]
Interesting. Those tools are probably all going away soon (integrated into the main UI), so this shouldn't be a problem for much longer...

**Comment by avaer** [comment]
Replaced all of the tools with in-window UI (camera, select, and transforms are all done by clicking now).

Therefore there should be no more conflict with the tools selection.
